# Generated by Django 5.2.8 on 2025-11-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
