# Generated by Django 5.2.8 on 2025-11-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0001_initial'),
        ('teachers', '0004_token_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestado',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.token'),
        ),
    ]
