# Generated by Django 5.2.8 on 2025-11-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0003_alter_mbtiresultado_encuestado'),
        ('VARK', '0002_alter_encuestado_grupo'),
        ('teachers', '0005_alter_token_options_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='encuestado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.alumno'),
        ),
        migrations.DeleteModel(
            name='Encuestado',
        ),
    ]
