# Generated by Django 5.2.8 on 2025-11-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0004_alter_opcionrespuesta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariopregunta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.pregunta'),
        ),
    ]
