# Generated by Django 5.2.8 on 2025-11-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0005_remove_mbtirespuestapregunta_respuesta_encuesta_and_more'),
        ('VARK', '0005_alter_formulariopregunta_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariopregunta',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='formulariopregunta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='encuestado',
        ),
        migrations.RemoveField(
            model_name='respuestaseleccionada',
            name='respuesta_encuesta',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='FormularioPregunta',
        ),
        migrations.DeleteModel(
            name='RespuestaEncuesta',
        ),
    ]
