# Generated by Django 5.2.8 on 2025-11-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0006_remove_formulariopregunta_formulario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaseleccionada',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.pregunta'),
        ),
    ]
