# Generated by Django 5.2.8 on 2025-11-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0007_alter_respuestaseleccionada_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionrespuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestaseleccionada',
            name='pregunta',
        ),
    ]
