# Generated by Django 5.2.8 on 2025-11-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0008_remove_opcionrespuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
