# Generated by Django 5.2.8 on 2025-11-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0009_delete_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaVark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Pregunta VARK',
                'verbose_name_plural': 'Preguntas VARK',
            },
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.preguntavark'),
        ),
        migrations.AddField(
            model_name='respuestaseleccionada',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.preguntavark'),
        ),
    ]
