# Generated by Django 5.2.8 on 2025-11-24 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0010_preguntavark_opcionrespuesta_pregunta_and_more'),
        ('teachers', '0005_alter_token_options_alumno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'Opción de Respuesta', 'verbose_name_plural': 'Opciones de Respuesta'},
        ),
        migrations.AlterModelOptions(
            name='respuestaseleccionada',
            options={'verbose_name': 'Respuesta Seleccionada', 'verbose_name_plural': 'Respuestas Seleccionadas'},
        ),
        migrations.AlterModelOptions(
            name='varkcategory',
            options={'verbose_name': 'Categoría VARK', 'verbose_name_plural': 'Categorías VARK'},
        ),
        migrations.CreateModel(
            name='FormularioControlVark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.alumno')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.token')),
            ],
            options={
                'verbose_name': 'Formulario Control VARK',
                'verbose_name_plural': 'Formularios Control VARK',
            },
        ),
    ]
