# Generated by Django 5.2.8 on 2025-11-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0011_alter_opcionrespuesta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaseleccionada',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AddField(
            model_name='respuestaseleccionada',
            name='control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='VARK.formulariocontrolvark'),
        ),
    ]
