# Generated by Django 5.2.8 on 2025-11-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0012_alter_respuestaseleccionada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'Opción VARK', 'verbose_name_plural': 'Opciones VARK'},
        ),
        migrations.AlterModelOptions(
            name='respuestaseleccionada',
            options={'verbose_name': 'Respuesta VARK', 'verbose_name_plural': 'Respuestas VARK'},
        ),
        migrations.AlterField(
            model_name='respuestaseleccionada',
            name='control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='VARK.formulariocontrolvark'),
        ),
        migrations.AlterField(
            model_name='respuestaseleccionada',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VARK.preguntavark'),
        ),
    ]
