# Generated by Django 5.2.8 on 2025-11-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0013_alter_opcionrespuesta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VARK.preguntavark'),
        ),
    ]
