# Generated by Django 5.2.8 on 2025-11-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0014_alter_opcionrespuesta_pregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariocontrolvark',
            options={'verbose_name': 'Test VARK', 'verbose_name_plural': 'Tests VARK'},
        ),
    ]
