# Generated by Django 5.2.8 on 2025-11-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0015_alter_formulariocontrolvark_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocontrolvark',
            name='resultado_auditivo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulariocontrolvark',
            name='resultado_kinestesico',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulariocontrolvark',
            name='resultado_lectura_escritura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formulariocontrolvark',
            name='resultado_visual',
            field=models.IntegerField(default=0),
        ),
    ]
