# Generated by Django 5.2.8 on 2025-11-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VARK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MBTIPreguntaDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_derecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_right', to='MBTI.mbtidimension')),
                ('dimension_izquierda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_left', to='MBTI.mbtidimension')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VARK.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='MBTIRespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_izquierda', models.IntegerField()),
                ('puntuacion_derecha', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VARK.pregunta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VARK.respuestaencuesta')),
            ],
        ),
    ]
