# Generated by Django 5.2.8 on 2025-11-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
        ('VARK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('energia', models.CharField(max_length=1)),
                ('informacion', models.CharField(max_length=1)),
                ('decisiones', models.CharField(max_length=1)),
                ('estilo_vida', models.CharField(max_length=1)),
                ('tipo_resultante', models.CharField(max_length=4)),
                ('encuestado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.encuestado')),
                ('formulario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.formulario')),
            ],
        ),
    ]
