# Generated by Django 5.2.8 on 2025-11-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_mbtiresultado'),
        ('teachers', '0005_alter_token_options_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtiresultado',
            name='encuestado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.alumno'),
        ),
    ]
