# Generated by Django 5.2.8 on 2025-11-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0003_alter_mbtiresultado_encuestado'),
        ('VARK', '0005_alter_formulariopregunta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtipreguntadimension',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.pregunta'),
        ),
        migrations.AlterField(
            model_name='mbtirespuestapregunta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VARK.pregunta'),
        ),
    ]
