# Generated by Django 5.2.8 on 2025-11-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0004_alter_mbtipreguntadimension_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtirespuestapregunta',
            name='respuesta_encuesta',
        ),
        migrations.RemoveField(
            model_name='mbtiresultado',
            name='formulario',
        ),
    ]
