# Generated by Django 5.2.8 on 2025-11-23 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0006_preguntambti_alter_mbtipreguntadimension_pregunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaMBTIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='mbtipreguntadimension',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBTI.preguntambtis'),
        ),
        migrations.AlterField(
            model_name='mbtirespuestapregunta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBTI.preguntambtis'),
        ),
        migrations.DeleteModel(
            name='PreguntaMBTI',
        ),
    ]
