# Generated by Django 5.2.8 on 2025-11-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0007_preguntambtis_alter_mbtipreguntadimension_pregunta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MBTIPreguntaDimension',
        ),
    ]
