# Generated by Django 5.2.8 on 2025-11-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0008_delete_mbtipreguntadimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtirespuestapregunta',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='PreguntaMBTIs',
        ),
    ]
