# Generated by Django 5.2.8 on 2025-11-24 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0009_remove_mbtirespuestapregunta_pregunta_and_more'),
        ('teachers', '0005_alter_token_options_alumno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mbtidimension',
            options={'verbose_name': 'Dimensión MBTI', 'verbose_name_plural': 'Dimensiones MBTI'},
        ),
        migrations.AlterModelOptions(
            name='mbtirespuestapregunta',
            options={'verbose_name': 'Respuesta MBTI', 'verbose_name_plural': 'Respuestas MBTI'},
        ),
        migrations.AlterModelOptions(
            name='mbtiresultado',
            options={'verbose_name': 'Resultado MBTI', 'verbose_name_plural': 'Resultados MBTI'},
        ),
        migrations.AlterField(
            model_name='mbtiresultado',
            name='encuestado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.alumno'),
        ),
        migrations.CreateModel(
            name='FormularioControlMBTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.alumno')),
            ],
            options={
                'verbose_name': 'Formulario de Control MBTI',
                'verbose_name_plural': 'Formularios de Control MBTI',
            },
        ),
        migrations.AddField(
            model_name='mbtirespuestapregunta',
            name='control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='MBTI.formulariocontrolmbti'),
        ),
        migrations.AddField(
            model_name='mbtiresultado',
            name='control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBTI.formulariocontrolmbti'),
        ),
        migrations.CreateModel(
            name='PreguntasMBTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('dimension_der', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_right', to='MBTI.mbtidimension')),
                ('dimension_izq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dim_left', to='MBTI.mbtidimension')),
            ],
            options={
                'verbose_name': 'Pregunta MBTI',
                'verbose_name_plural': 'Preguntas MBTI',
            },
        ),
        migrations.AddField(
            model_name='mbtirespuestapregunta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBTI.preguntasmbti'),
        ),
    ]
