# Generated by Django 5.2.8 on 2025-11-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0010_alter_mbtidimension_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariocontrolmbti',
            options={'verbose_name': 'Test MBTI', 'verbose_name_plural': 'Tests MBTI'},
        ),
    ]
