# Generated by Django 5.2.8 on 2025-11-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0011_alter_formulariocontrolmbti_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtiresultado',
            name='encuestado',
        ),
        migrations.RemoveField(
            model_name='mbtiresultado',
            name='fecha',
        ),
    ]
