# Generated by Django 5.2.8 on 2025-11-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0012_remove_mbtiresultado_encuestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocontrolmbti',
            name='decisiones',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariocontrolmbti',
            name='energia',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariocontrolmbti',
            name='estilo_vida',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariocontrolmbti',
            name='informacion',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulariocontrolmbti',
            name='tipo_resultante',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MBTIResultado',
        ),
    ]
