# Generated by Django 5.2.8 on 2025-11-24 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0014_alter_formulariocontrolmbti_token'),
        ('teachers', '0005_alter_token_options_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontrolmbti',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.token'),
        ),
    ]
