# Generated by Django 5.2.8 on 2025-11-24 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0015_alter_formulariocontrolmbti_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtirespuestapregunta',
            name='control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='MBTI.formulariocontrolmbti'),
        ),
        migrations.AlterField(
            model_name='mbtirespuestapregunta',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MBTI.preguntasmbti'),
        ),
    ]
